bank_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('bank_api.urls')),
    path("", include('bank_ui.urls'))

]

bank_ui/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('', views.home, name='home'),
    path('balance/', views.balance, name='balance'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('deposit/', views.deposit, name='deposit'),
    path('transfer/', views.transfer, name='transfer'),
]

bank_api/models.py
from django.db import models
from django.contrib.auth.models import User


class Bank_Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    account_number = models.IntegerField()
    balance = models.DecimalField(default=0, max_digits=20, decimal_places=2)

    def to_dict(self) -> dict:
        return {
            'id': self.id,
            'account_number': self.account_number,
            'balance': self.balance
        }

    def __repr__(self) -> str:
        return f'{self.id, self.user.username, self.account_number, self.balance}'

    def __str__(self) -> str:
        return f'{self.account_number}'


class Transaction(models.Model):
    transaction_id = models.IntegerField()
    account = models.ForeignKey(Bank_Account, on_delete=models.CASCADE)
    from_account_number = models.IntegerField(blank=True, null=True)
    to_account_number = models.IntegerField(blank=True, null=True)
    amount = models.DecimalField(default=0, max_digits=20, decimal_places=2)
    date = models.DateField(auto_now_add=True)
    t_type = models.CharField(max_length=8, choices=[(
        "deposit", "Deposit"), ("withdraw", "Withdraw"), ("sent", "Sent"), ("received", "Received")], default="Null")
    description = models.CharField(max_length=100, blank=True, default='')

    def __str__(self) -> str:
        return f'{self.id}, {self.account.account_number} -> {self.to_account_number}, {self.t_type}'

    def to_dict(self) -> dict:
        return {
            'id': self.id,
            'account_number': self.account.account_number,
            "from_account_number": self.from_account_number,
            'to_account_number': self.to_account_number,
            'amount': self.amount,
            'date': self.date,
            't_type': self.t_type,
            'description': self.description
        }

templates/balance.html
{% extends "base.html" %}

{% load static %}

{% block Title %}Sun Bank - Balance{% endblock %}

{% block Content %}
<div id="user-balance">Balance: {{ request.user.bank_account.balance }}$</div>
<div class="table-div">
<table class="transactions-history-table">
    <thead>
        <tr>
            <th>Transaction ID</th>
            <th>Amount</th>
            <th>Type</th>
            <th>Date</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        {% if request.user.bank_account.transaction_set.all|length > 0 %}
            {% for transaction in request.user.bank_account.transaction_set.all %}
                <tr>
                    <td>{{ transaction.transaction_id }}</td>
                    <td>
                        {% if transaction.t_type == "sent" or transaction.t_type == "withdraw" %}
                            -
                        {% else %}
                            +
                        {% endif %}
                        {{ transaction.amount }}
                    </td>
                    <td>{{ transaction.t_type|title }}</td>
                    <td>{{ transaction.date }}</td>
                    <td>{{ transaction.description|title }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="6">No Transactions Yet</td>
            </tr>   
        {% endif %}
    </tbody>
</table>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block Title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="{% static 'js/functions.js' %}"></script>
</head>
<body>
    <div id="root">
        <div id="nav-bar">
            <a href="{% url 'home' %}"><button class="nav-button">Home</button></a>
            {% if user.is_authenticated %}
                <a href="{% url 'balance' %}"><button class="nav-button">Balance</button></a>
                <a href="{% url 'deposit' %}"><button class="nav-button">Deposit</button></a>
                <a href="{% url 'withdraw' %}"><button class="nav-button">Withdraw</button></a>
                <a href="{% url 'transfer' %}"><button class="nav-button">Transfer</button></a>
                <a href="{% url 'logout' %}"><button class="nav-button">Logout</button></a>
            {% else %}
                <a href="{% url 'login' %}"><button class="nav-button">Login</button></a>
                <a href="{% url 'register' %}"><button class="nav-button">Register</button></a>

            {% endif %}

        </div>
        <div id="tab-content">
        {% block Content %}{% endblock %}
        </div>
    </div>
    {% block JavaScript %}{% endblock %}
</body>
</html>

templates/deposit.html
{% extends "base.html" %}

{% load static %}

{% load filters %}

{% block Title %}Sun Bank - Deposit{% endblock %}
{% block Content %}
    <div id="user-balance">Balance: {{ request.user.bank_account.balance }}$</div>
    <div id="action-form">
        <label for="amount">Amount:</label>
        <input type="number" id="amount" placeholder="Amount">
        <label for="description">Description:</label>
        <input type="text" id="description" placeholder="Description">
        <button onclick="depositAction()" class="button">Deposit</button>
        <div id="action-message">{{ msg }}</div>
    </div>
    <div class="table-div">
    <table class="transactions-history-table">
        <thead>
            <tr>
                <th>Transaction ID</th>
                <th>Amount</th>
                <th>Date</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% if request.user.bank_account.transaction_set.all|transactions_type_filter:"deposit"|length > 0 %}
                {% for transaction in request.user.bank_account.transaction_set.all|transactions_type_filter:"deposit"%}
                    <tr>
                        <td>{{ transaction.transaction_id }}</td>
                        <td>+ {{ transaction.amount }}</td>
                        <td>{{ transaction.date }}</td>
                        <td>{{ transaction.description|title }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="6">No Deposits Yet</td>
                </tr>   
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}
{% block JavaScript %}
<script>
    function depositAction(){
        let amountElement = document.getElementById("amount");
        let descriptionElement = document.getElementById("description");
        axios.post('/api/deposit/', {amount: Number(amountElement.value), description: descriptionElement.value},{headers: {
            'X-CSRFTOKEN': getCSRFToken()}})
            .then((response)=>{
                console.log(response.data);
                amountElement.value = ""
                descriptionElement.value = ""
                let currentUrl = window.location.href;
                let cleanURL = currentUrl.split('?')[0]
                const urlWithParams = new URL(cleanURL);
                urlWithParams.searchParams.append("msg", response.data.result)
                window.location.replace(urlWithParams)
            })
    }
</script>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% load static %}

{% load filters %}

{% block Title %}Sun Bank - Home{% endblock %}

{% block Content %}
<div id="account-info">
    <div id="user-greeting">Hello {{ user|title  }}</div>
    |
    <div id="user-account-number">Account Number: {{ request.user.bank_account.account_number }}</div>
</div>
<div id="home-user-balance">Balance: {{ request.user.bank_account.balance }}$</div>
<div id="month-statistics-tab">
    <div id="month-statistics-tab-header">Month Statistics:</div>
    <div id="month-statistics-tab-income">Income: +{{ request.user.bank_account.transaction_set.all|filter_income_expense:"income" }}$</div>
    <div id="month-statistics-tab-expense">Expense: -{{ request.user.bank_account.transaction_set.all|filter_income_expense:"expense" }}$</div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% load static %}

{% block Title %}Sun Bank - Login{% endblock %}

{% block Content %}
<form action="{% url 'login' %}" method="POST" id="login-form">
    {% csrf_token %}
    {{ login_form }}
    <input type="submit" value="Login" class="button" id="login-submit-button">
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
        </div>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% load static %}

{% block Title %}Sun Bank - Register{% endblock %}

{% block Content %}
<form action="{% url 'register' %}" method="POST">
 {% csrf_token %}
 {{ register_form }}
 <input type="submit" class="button" value="Register">
</form>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
        </div>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

templates/transfer.html
{% extends "base.html" %}

{% load static %}

{% load filters %}

{% block Title %}Sun Bank - Transfer{% endblock %}

{% block Content %}
<div id="user-balance">Balance: {{ request.user.bank_account.balance }}$</div>
<div id="action-form">
    <label for="to-account">To:</label>
    <input type="number" id="to-account" placeholder="Account Number">
    <label for="amount">Amount:</label>
    <input type="number" id="amount" placeholder="Amount">
    <label for="description">Description:</label>
    <input type="text" id="description" placeholder="Description">
    <button onclick="transferAction()" class="button">Transfer</button>
    <div id="action-message">{{ msg }}</div>
<div class="table-div">
<table class="transactions-history-table">
    <thead>
        <tr>
            <th>Transaction ID</th>
            <th>From</th>
            <th>To</th>
            <th>Amount</th>
            <th>Type</th>
            <th>Date</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        {% if request.user.bank_account.transaction_set.all|transactions_type_filter:"transfer"|length > 0 %}
        {% for transaction in request.user.bank_account.transaction_set.all|transactions_type_filter:"transfer" %}
                <tr>
                    <td>{{ transaction.transaction_id }}</td>
                    <td>{{ transaction.from_account_number }}</td>
                    <td>{{ transaction.to_account_number }}</td>
                    <td>
                        {% if transaction.t_type == "sent" %}
                            - {{ transaction.amount }}
                        {% else %}
                            + {{ transaction.amount }}
                        {% endif %}
                    </td>
                    <td>{{ transaction.t_type|title }}</td>
                    <td>{{ transaction.date }}</td>
                    <td>{{ transaction.description|title }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="6">No Transactions Yet</td>
            </tr>   
        {% endif %}
    </tbody>
</table>
</div>
{% endblock %}
{% block JavaScript %}
<script>
    function transferAction(){
        let amountElement = document.getElementById("amount");
        let descriptionElement = document.getElementById("description");
        let ToAccountElement = document.getElementById("to-account")
        axios.post('/api/transfer/', {amount: Number(amountElement.value), to_account_number:ToAccountElement.value, description: descriptionElement.value},{headers: {
            'X-CSRFTOKEN': getCSRFToken()}})
        .then((response)=>{
            console.log(response.data);    
            amountElement.value = ""
            descriptionElement.value = ""
            let currentUrl = window.location.href;
            let cleanURL = currentUrl.split('?')[0]
            const urlWithParams = new URL(cleanURL);
            urlWithParams.searchParams.append("msg", response.data.result)
            window.location.replace(urlWithParams)
            })
    }
</script>
{% endblock %}

templates/withdraw.html
{% extends "base.html" %}

{% load static %}

{% load filters %}

{% block Title %}Sun Bank - Withdraw{% endblock %}

{% block Content %}
    <div id="user-balance">Balance: {{ request.user.bank_account.balance }}$</div>
    <div id="action-form">
        <label for="amount">Amount:</label>
        <input type="number" id="amount" placeholder="Amount">
        <label for="description">Description:</label>
        <input type="text" id="description" placeholder="Description">
        <button onclick="withdrawAction()" class="button">Withdraw</button>
        <div id="action-message">{{ msg }}</div>
    <div class="table-div">
    <table class="transactions-history-table">
        <thead>
            <tr>
                <th>Transaction ID</th>
                <th>Amount</th>
                <th>Date</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% if request.user.bank_account.transaction_set.all|transactions_type_filter:"withdraw"|length > 0 %}
                {% for transaction in request.user.bank_account.transaction_set.all|transactions_type_filter:"withdraw"%}
                    <tr>
                        <td>{{ transaction.transaction_id }}</td>
                        <td>- {{ transaction.amount }}</td>
                        <td>{{ transaction.date }}</td>
                        <td>{{ transaction.description|title }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="6">No Withdraws Yet</td>
                </tr>   
            {% endif %}
        </tbody>
    </table>
    </div>
{% endblock %}
{% block JavaScript %}
<script>
    function withdrawAction(){
        let amountElement = document.getElementById("amount");
        let descriptionElement = document.getElementById("description");
        axios.post('/api/withdraw/', {amount: Number(amountElement.value), description: descriptionElement.value},{headers: 
            {'X-CSRFTOKEN': getCSRFToken()}})
        .then((response)=>{
            console.log(response.data);    
            amountElement.value = ""
            descriptionElement.value = ""
            let currentUrl = window.location.href;
            let cleanURL = currentUrl.split('?')[0]
            const urlWithParams = new URL(cleanURL);
            urlWithParams.searchParams.append("msg", response.data.result)
            window.location.replace(urlWithParams)
            })
    }
</script>
{% endblock %}